import type { Interpretation, Profile } from "@/lib/api";

const KIND_LABEL: Record<string, string> = {
  observed_fact: "observed",
  governed_knowledge: "governed",
  inference: "inference",
  recommendation: "recommendation",
};

/** "Would I sign my name to this?" answered in one glance, without scrolling —
 *  computed straight from `ProfileFacts` and the claim counts, never
 *  requiring the analyst to read a claim to know how many there are. Sticky
 *  on wide viewports (`.verdict-card`, ≥1100px) so it stays visible while the
 *  evidence column, which can run long, scrolls past it.
 *
 *  PR-7 adds one line from the v2 facts — time coverage, constant columns,
 *  dates carrying placeholder values — composed from what the profiler
 *  recorded, never generated, and absent for a profile written by v1. */
export default function VerdictCard({
  profile,
  interpretation,
}: {
  profile: Profile;
  interpretation: Interpretation;
}) {
  const { facts } = profile;
  const { claims, signals, headline } = interpretation.content;

  const counts = claims.reduce<Record<string, number>>((acc, claim) => {
    acc[claim.kind] = (acc[claim.kind] ?? 0) + 1;
    return acc;
  }, {});
  const riskCount = signals.filter((s) => s.kind === "risk").length;
  // Bookkeeping about discarded model output (`severity: "info"`) never
  // counts as a blocker - only a real unknown the model declined to guess.
  const blockers = signals.filter((s) => s.severity === "blocker").length;

  const constant = facts.columns.filter((c) => c.constant).length;
  const sentinelDates = facts.columns.filter(
    (c) => c.hint === "date" && (c.sentinel_count ?? 0) > 0,
  ).length;
  const v2Parts: string[] = [];
  if (facts.time_coverage) {
    v2Parts.push(`time coverage ${facts.time_coverage.min} → ${facts.time_coverage.max}`);
  }
  if (constant) v2Parts.push(`${constant} constant column${constant === 1 ? "" : "s"}`);
  if (sentinelDates) {
    v2Parts.push(
      `${sentinelDates} date${sentinelDates === 1 ? "" : "s"} with placeholder values`,
    );
  }

  return (
    <div className="card verdict-card">
      <span className="panel-label">Verdict</span>
      {/* Composed by `_assemble`/`_validate` from the final signals, never
       *  generated by the model - see `Signal`'s docstring in workflow/models.py. */}
      <p className="verdict-headline">{headline}</p>
      <p className="verdict-facts mono">
        {facts.row_count.toLocaleString()} rows · {facts.columns.length} columns ·{" "}
        {facts.phi_candidates.length} PHI candidates
        <br />
        key{" "}
        {facts.candidate_keys.length
          ? facts.candidate_keys.map((k) => k.join(" + ")).join(", ")
          : "none found"}{" "}
        · {facts.duplicate_rows} duplicate rows
        {v2Parts.length ? (
          <>
            <br />
            {v2Parts.join(" · ")}
          </>
        ) : null}
      </p>
      <p className="verdict-claim-counts">
        {(["observed_fact", "governed_knowledge", "inference", "recommendation"] as const).map(
          (kind, index) => (
            <span key={kind}>
              {index > 0 ? " · " : ""}
              {counts[kind] ?? 0} {KIND_LABEL[kind]}
              {(counts[kind] ?? 0) === 1 ? "" : "s"}
            </span>
          ),
        )}
        {riskCount ? ` · ${riskCount} risk${riskCount === 1 ? "" : "s"}` : ""}
        {blockers ? ` · ${blockers} unknown${blockers === 1 ? "" : "s"}` : ""}
      </p>
      {blockers ? (
        <p className="alert warn verdict-blockers">
          Blockers: {blockers} unknown{blockers === 1 ? "" : "s"} unresolved — see Signals below
        </p>
      ) : null}
    </div>
  );
}
